# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # AIDEV-NOTE: VMware Workstation guest modules
  boot.initrd.availableKernelModules = [ "ahci" "pata_acpi" "ata_generic" "sd_mod" "mpt3sas" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "vmwgfx" "vmw_balloon" "vmw_vmci" "vsock" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e8c08e93-7c73-4f1b-990a-ce647c8cbb6f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5C9F-4A3E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
