# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.

{ self, inputs, ... }: {

  flake.nixosModules.razerBladeHardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      boot.initrd.kernelModules = [
        "i915"
        "nvidia"
      ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];
      boot.kernelParams = [
        "button.lid_init_state=open"
        # "nvidia.NVreg_PreserveVideoMemoryAllocations=1"  # Para suspender correctamente
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };

}
